/* 짧은 이야기 컷신 12편 (스토리 리드, 리뷰 1008 제안)
   장면 모양은 MQ_JOB.scenes와 같다: {bg, cast:[[열쇠,'L'|'C'|'R']], who, text:[..], doc:{t,rows,bad}, fx, amt, sfx}
   선택지(choice)는 넣지 않았다. 짧은 컷신은 보는 것이지 시험이 아니다.
   {n} {rev} {tier} {lv} {mq} {bg} {face} {name}은 csPlay가 재생 직전에 채운다.
   cast의 'pet_bird'는 portraitSrc에 pet_ 그림을 꺼내는 세 줄을 더해야 보인다(story.md 4절). */
var CS_STORY = {
 firstq: { title: '첫 단추', sub: '퀘스트 하나를 끝낸 날', reward: null,
  scenes: [
   { bg: 'town', fx: 'fade', cast: [['hero', 'C']],
     text: ['첫 퀘스트를 끝냈다.', '머리가 조금', '덜 복잡해졌다.'] },
   { bg: 'town', cast: [['hero', 'L'], ['halbae', 'R']], who: '귀인 할배',
     text: ['허허, 첫 단추를', '뀄구먼.'] },
   { bg: 'town', cast: [['hero', 'L'], ['halbae', 'R']], who: '나',
     text: ['이거 하나 안다고', '뭐가 달라질까요?'] },
   { bg: 'town', cast: [['hero', 'L'], ['halbae', 'R']], who: '귀인 할배',
     text: ['하나를 알면 다음', '서류가 덜 무섭네.', '그게 쌓이는 거야.'] },
   { bg: 'town',
     doc: { t: '퀘스트를 풀면', rows: [['경험치', '레벨이 오른다'], ['코인', '살림과 보증금'], ['스탯', '집·밥·옷·돈·일'], ['틀린 문항', '내일 복습']], bad: [] },
     text: ['푼 만큼 돈과 스탯이', '쌓인다. 틀린 건', '내일 다시 나온다.'] },
   { bg: 'town', cast: [['hero', 'L'], ['halbae', 'R']], who: '귀인 할배',
     text: ['느낌표(!) 뜬 사람이', '또 기다리는구먼.', '천천히 가 보세.'] } ] },

 firstfail: { title: '틀려도 괜찮네', sub: '처음 퀘스트를 놓친 날', reward: null,
  scenes: [
   { bg: 'night', fx: 'rain', cast: [['hero', 'C']],
     text: ['반도 못 맞혔다.', '보상은 없었다.'] },
   { bg: 'night', fx: 'rain', cast: [['hero', 'L'], ['halbae', 'R']], who: '귀인 할배',
     text: ['허허, 표정이 영', '안 좋구먼.'] },
   { bg: 'night', fx: 'rain', cast: [['hero', 'L'], ['halbae', 'R']], who: '나',
     text: ['다 아는 줄 알았는데', '하나도 모르겠어요.'] },
   { bg: 'night', fx: 'rain', cast: [['hero', 'L'], ['halbae', 'R']], who: '귀인 할배',
     text: ['여기서 틀리면', '돈이 안 드네.', '밖에서 틀리면 들지.'] },
   { bg: 'night',
     doc: { t: '복습 상자', rows: [['틀린 문항', '내일 다시'], ['또 맞히면', '3일 · 7일 뒤'], ['계속 맞히면', '상자에서 졸업'], ['보상', '복습도 코인']], bad: [] },
     text: ['틀린 문항은', '복습 상자에 담겼다.'] },
   { bg: 'night', cast: [['hero', 'L'], ['halbae', 'R']], who: '귀인 할배',
     text: ['나도 처음엔 다 틀렸네.', '...아주 옛날 일이야.', '다시 해 보세.'] } ] },

 lv2: { title: '살림 다섯 가지', sub: '레벨 2 · 스탯 이야기', reward: null,
  scenes: [
   { bg: 'town', fx: 'flash', sfx: 'level', cast: [['hero', 'C']],
     text: ['레벨 2가 됐다.', '몸이 조금 가볍다.'] },
   { bg: 'town', cast: [['hero', 'L'], ['halbae', 'R']], who: '귀인 할배',
     text: ['허허, 한 고개 넘었구먼.', '이참에 살림 얘기를', '해 두세.'] },
   { bg: 'town',
     doc: { t: '살림 다섯 가지', rows: [['집', '거처가 열린다 · 방어'], ['밥', '체력'], ['옷', '매력'], ['돈 · 일', '자금 · 경험']], bad: [] },
     who: '귀인 할배', text: ['사는 게 결국', '집, 밥, 옷, 돈, 일', '다섯 가지야.'] },
   { bg: 'town', cast: [['hero', 'L'], ['halbae', 'R']], who: '귀인 할배',
     text: ['집 퀘스트를 풀면', '집 스탯이 올라서', '더 나은 방이 열리네.'] },
   { bg: 'town', cast: [['hero', 'L'], ['halbae', 'R']], who: '귀인 할배',
     text: ['고약한 사람들도', '있네. 그 스탯이 차야', '맞설 수 있지.'] },
   { bg: 'town', cast: [['hero', 'L'], ['halbae', 'R']], who: '나',
     text: ['어느 것부터', '올려야 해요?'] },
   { bg: 'town', cast: [['hero', 'L'], ['halbae', 'R']], who: '귀인 할배',
     text: ['급한 것부터 하게.', '지금 자네는...', '잘 곳부터 아닌가?'] } ] },

 home4: { title: '문 달린 방', sub: '고시원 첫날', reward: { coin: 50 },
  scenes: [
   { bg: 'gosiwon', fx: 'fade', cast: [['hero', 'C']],
     text: ['고시원 방 한 칸.', '팔을 벌리면', '양쪽 벽이 닿는다.'] },
   { bg: 'gosiwon', cast: [['hero', 'C']], who: '나',
     text: ['그래도 문이 있다.', '잠글 수 있는 문.'] },
   { bg: 'gosiwon', cast: [['hero', 'L'], ['halbae', 'R']], who: '귀인 할배',
     text: ['허허, 좁아도 내 방이구먼.', '첫날 밤이 제일', '길 걸세.'] },
   { bg: 'gosiwon',
     doc: { t: '고시원 들어가면', rows: [['창문', '있는 방이 더 비싸다'], ['공용', '주방·화장실·세탁'], ['입실료', '이체 기록 남기기'], ['전입신고', '할 수 있다']], bad: [] },
     text: ['고시원도 전입신고를', '할 수 있다.', '주소가 생긴다.'] },
   { bg: 'night', cast: [['hero', 'L'], ['halbae', 'R']], who: '귀인 할배',
     text: ['벽이 얇으니', '이어폰 하나 챙기게.', '...나도 그랬거든.'] },
   { bg: 'night', fx: 'confetti', cast: [['hero', 'C']],
     text: ['다음 방은', '집 스탯을 올리면', '열린다.'] } ] },

 home6: { title: '첫 월세 방', sub: '원룸 월세 첫날', reward: { coin: 100 },
  scenes: [
   { bg: 'town', fx: 'fade', cast: [['hero', 'L'], ['halbae', 'R']], who: '귀인 할배',
     text: ['허허, 드디어 원룸이구먼.', '화장실이 방 안에', '있는 집이야.'] },
   { bg: 'town',
     doc: { t: '월세 계약서', rows: [['보증금', '500만 원'], ['월세', '45만 원'], ['관리비', '7만 원 별도'], ['특약', '도배는 세입자 부담']], bad: [3] },
     who: '귀인 할배', text: ['빨간 줄 보이나?', '특약은 소리 내서', '읽어 보게.'] },
   { bg: 'phone', fx: 'fade', cast: [['hero', 'C']],
     text: ['짐을 다 풀고 나니', '밤 열한 시.', '라면 물을 올렸다.'] },
   { bg: 'phone', cast: [['hero', 'L'], ['halbae', 'R']], who: '귀인 할배',
     text: ['월세는 매달 나가는', '돈이야. 월급날', '바로 빠지게 해 두게.'] },
   { bg: 'phone', cast: [['hero', 'L'], ['halbae', 'R']], who: '귀인 할배',
     text: ['월세 낸 기록은', '버리지 말게. 연말정산', '때 쓸 수도 있네.'] },
   { bg: 'phone', fx: 'confetti', cast: [['hero', 'C']],
     text: ['창밖에 불빛이 많다.', '오늘부터 여기가', '우리 동네다.'] } ] },

 home8: { title: '방이 둘', sub: '투룸 전세로 옮긴 날', reward: { coin: 150 },
  scenes: [
   { bg: 'apartment', fx: 'fade', cast: [['hero', 'C']],
     text: ['두 번째 전세 계약.', '이번엔 도장 찍는', '손이 덜 떨렸다.'] },
   { bg: 'livingroom', cast: [['hero', 'L'], ['halbae', 'R']], who: '귀인 할배',
     text: ['허허, 방이 둘이구먼.', '하나는 자고, 하나는', '뭘 할 텐가?'] },
   { bg: 'livingroom', cast: [['hero', 'L'], ['halbae', 'R']], who: '나',
     text: ['책상 놓고 공부요.', '자격증 하나 따려고요.'] },
   { bg: 'livingroom', cast: [['hero', 'L'], ['halbae', 'R']], who: '귀인 할배',
     text: ['좋지. 그리고 하나 더.', '전 집 보증금은', '다 돌려받았나?'] },
   { bg: 'livingroom',
     doc: { t: '이사 날 체크', rows: [['전 집', '보증금 돌려받기'], ['새 집', '전입신고·확정일자'], ['보증보험', '가입 확인'], ['전 집 열쇠', '반납']], bad: [] },
     text: ['나가는 날과', '들어가는 날이 겹치면', '순서가 중요하다.'] },
   { bg: 'livingroom', fx: 'confetti', cast: [['hero', 'L'], ['halbae', 'R']], who: '귀인 할배',
     text: ['이제 집 얘기는', '반쯤 끝났네.', '남은 반은 내 집이야.'] } ] },

 home12: { title: '불 켜진 창', sub: '첫 아파트 59㎡', reward: { coin: 200 },
  scenes: [
   { bg: 'apartment', fx: 'fade', cast: [['hero', 'L'], ['partner', 'R']],
     text: ['아파트 단지 정문.', '경비실 아저씨가', '고개를 끄덕였다.'] },
   { bg: 'apartment', cast: [['hero', 'L'], ['partner', 'R']], who: '배우자',
     text: ['여기가 우리 동이야?', '몇 층이랬지?'] },
   { bg: 'livingroom', cast: [['hero', 'L'], ['partner', 'C'], ['halbae', 'R']], who: '귀인 할배',
     text: ['허허, 방이 셋이구먼.', '고시원 벽', '기억하나?'] },
   { bg: 'livingroom', cast: [['hero', 'L'], ['partner', 'C'], ['halbae', 'R']], who: '나',
     text: ['팔 벌리면 닿던 벽이요.', '어떻게 잊어요.'] },
   { bg: 'livingroom',
     doc: { t: '내 집이면 오는 것', rows: [['관리비', '매달 · 겨울엔 더'], ['장기수선충당금', '소유자 몫'], ['재산세', '7월 · 9월'], ['고장', '내 집은 내가']], bad: [] },
     who: '귀인 할배', text: ['내 집이 되면', '고지서도 내 이름으로', '오네.'] },
   { bg: 'night', fx: 'confetti', cast: [['hero', 'L'], ['partner', 'C'], ['halbae', 'R']], who: '귀인 할배',
     text: ['불 켜진 창 하나가', '자네 집이라니.', '...좋구먼, 참.'] } ] },

 boss1: { title: '처음 이긴 날', sub: '첫 보스를 이겼다', reward: null,
  /* 첫 장면만 보스마다 다르다. csPlay가 BOSS_FIRST[b.id]를 앞에 붙이고 {bg}{face}를 채운다 */
  scenes: [
   { bg: '{bg}', cast: [['hero', 'C']],
     text: ['상대가 먼저', '자리를 떴다.', '손이 아직 떨린다.'] },
   { bg: 'night', fx: 'fade', cast: [['hero', 'L'], ['halbae', 'R']], who: '귀인 할배',
     text: ['허허, 봤나?', '목소리 큰 쪽이', '이기는 게 아니야.'] },
   { bg: 'night', cast: [['hero', 'L'], ['halbae', 'R']], who: '귀인 할배',
     text: ['종이 한 장, 숫자 하나.', '그걸 아는 쪽이', '이기는 거지.'] },
   { bg: 'night', cast: [['hero', 'L'], ['halbae', 'R']], who: '나',
     text: ['할아버지는 이런 사람', '어떻게 알아봐요?'] },
   { bg: 'night', cast: [['hero', 'L'], ['halbae', 'R']], who: '귀인 할배',
     text: ['...한 번 당해 봤거든.', '아주 크게.', '자네는 안 당하면 되네.'] },
   { bg: 'night', fx: 'confetti', cast: [['hero', 'C']],
     text: ['다른 고약한 사람들도', '어딘가에서', '기다리고 있다.'] } ] },

 streak7: { title: '이레째 아침', sub: '7일 연속 출석', reward: null,
  scenes: [
   { bg: 'phone', cast: [['hero', 'C']],
     text: ['아침 여섯 시 오십 분.', '알람보다 먼저', '창문이 울렸다.'] },
   { bg: 'phone', sfx: 'good', cast: [['hero', 'L'], ['pet_bird', 'R']],
     text: ['참새 한 마리가', '창틀에 앉아 있다.', '짹.'] },
   { bg: 'station', fx: 'fade', cast: [['hero', 'L'], ['halbae', 'R']], who: '귀인 할배',
     text: ['허허, 이레를 내리', '왔구먼. 참새가', '먼저 알아봤나 보네.'] },
   { bg: 'station', cast: [['hero', 'L'], ['halbae', 'R']], who: '귀인 할배',
     text: ['돈 모으는 것도', '공부도, 결국은', '매일 조금씩이야.'] },
   { bg: 'station',
     doc: { t: '연속 출석', rows: [['3일부터', '출석 코인 2배'], ['7일부터', '출석 코인 3배'], ['14일', '전기자전거'], ['30일', '￦500']], bad: [] },
     text: ['내일도 오면', '출석 코인이 3배다.'] },
   { bg: 'station', fx: 'confetti', cast: [['hero', 'L'], ['pet_bird', 'C'], ['halbae', 'R']], who: '귀인 할배',
     text: ['출근길 동무가', '생겼구먼.', '같이 가 보세.'] } ] },

 tax: { title: '13월의 월급', sub: '연말정산 철', reward: { coin: 130, yearly: 1 },
  scenes: [
   { bg: 'office', fx: 'fade', cast: [['hero', 'L'], ['peerf', 'R']], who: '입사 동기',
     text: ['연말정산 메일 왔어요?', '작년에 토해 냈다는', '사람도 있대요.'] },
   { bg: 'office', cast: [['hero', 'L'], ['halbae', 'R']], who: '귀인 할배',
     text: ['허허, 1월이구먼.', '1년 치 영수증을', '맞춰 보는 달이야.'] },
   { bg: 'phone',
     doc: { t: '연말정산 순서', rows: [['1월 중순', '간소화 자료 열림'], ['회사 일정', '서류 내기'], ['빠진 것', '직접 챙기기'], ['2~3월', '월급에 정산']], bad: [] },
     text: ['간소화 자료에', '안 잡히는 것도 있다.'] },
   { bg: 'phone', cast: [['hero', 'L'], ['halbae', 'R']], who: '귀인 할배',
     text: ['월세 사는 사람은', '월세 공제 조건을', '꼭 따져 보게.'] },
   { bg: 'phone', cast: [['hero', 'L'], ['halbae', 'R']], who: '나',
     text: ['안경값 영수증도', '따로 챙기래요.'] },
   { bg: 'phone', fx: 'confetti', cast: [['hero', 'L'], ['halbae', 'R']], who: '귀인 할배',
     text: ['돌려받는 돈은', '원래 자네 돈이야.', '공짜가 아니고.'] } ] },

 back: { title: '돌아온 날', sub: '사흘 넘게 쉬고 온 날', reward: { coin: 100, every: 14 },
  scenes: [
   { bg: 'town', fx: 'fade', cast: [['hero', 'C']],
     text: ['{n}일 만의 동네.', '편의점 간판이', '바뀌어 있다.'] },
   { bg: 'town', cast: [['hero', 'L'], ['halbae', 'R']], who: '귀인 할배',
     text: ['허허, 왔구먼.', '바빴던 모양이야.', '밥은 먹고 다녔나?'] },
   { bg: 'town', cast: [['hero', 'L'], ['halbae', 'R']], who: '나',
     text: ['정신이 없어서요.', '다 까먹었을 것', '같아요.'] },
   { bg: 'town', cast: [['hero', 'L'], ['halbae', 'R']], who: '귀인 할배',
     text: ['까먹는 게 정상이야.', '복습 상자에 {rev}개가', '기다리고 있네.'], alt: { rev0: ['까먹는 게 정상이야.', '그래도 복습 상자는', '비어 있구먼. 장하네.'] } },
   { bg: 'town',
     doc: { t: '지금 내 자리', rows: [['거처', '{tier}'], ['레벨', 'Lv.{lv}'], ['다음 메인', '{mq}'], ['연속 출석', '오늘부터 1일']], bad: [] },
     text: ['연속 기록은', '오늘부터 다시 센다.'] },
   { bg: 'town', cast: [['hero', 'L'], ['halbae', 'R']], who: '귀인 할배',
     text: ['오늘은 하나만 하세.', '하나면 충분해.'] } ] },

 memory: { title: '하루 네 번 버스', sub: '할배의 옛날 얘기', reward: null,
  scenes: [
   { bg: 'night', cast: [['hero', 'L'], ['halbae', 'R']], who: '귀인 할배',
     text: ['오늘은 공부 말고', '옛날 얘기나', '하나 하세.'] },
   { bg: 'hometown', fx: 'fade', who: '귀인 할배',
     text: ['산 너머 버스가', '하루 네 번 서는', '마을이 있었네.'] },
   { bg: 'hometown', who: '귀인 할배',
     text: ['스무 몇 살에', '그 버스를 타고', '마을을 떠났지.'] },
   { bg: 'hometown', cast: [['hero', 'C']], who: '나',
     text: ['...어? 우리 동네도', '버스가 하루', '네 번인데.'] },
   { bg: 'night', cast: [['hero', 'L'], ['halbae', 'R']], who: '귀인 할배',
     text: ['허허, 시골 버스는', '다 그렇다네.', '...다 그래.'] },
   { bg: 'night', cast: [['hero', 'L'], ['halbae', 'R']], who: '귀인 할배',
     text: ['그때 누가 서류 보는 법', '하나만 알려 줬으면', '했지.'] },
   { bg: 'night', fx: 'fade', cast: [['hero', 'C']],
     text: ['할배는 그 뒤로', '말이 없었다.', '별이 많은 밤이었다.'] } ] }
};
/* 첫 보스 승리: 보스마다 첫 장면과 배경 */
var BOSS_FIRST = {
 jeonse: { bg: 'apartment', scene: { bg: 'apartment', fx: 'shake', cast: [['hero', 'L'], ['boss', 'R']], who: '전세 먹튀 집주인',
   text: ['...알았어, 알았다고.', '만기 날짜 맞춰서', '돌려줄게.'] } },
 mlm: { bg: 'cafe', scene: { bg: 'cafe', fx: 'shake', cast: [['hero', 'L'], ['mlmf', 'R']], who: '다단계 선배',
   text: ['...너 좀 변했다?', '예전엔 내 말이면', '다 들었잖아.'] } },
 fp: { bg: 'bank', scene: { bg: 'bank', fx: 'shake', cast: [['hero', 'L'], ['fp', 'R']], who: '자칭 재무설계사',
   text: ['...수수료 얘기는', '다음에 하시죠.', '오늘은 이만.'] } }
};
